


```{r}
setwd("~/Desktop/FXR analysis/Fxr/Data")
shared = read.csv("shared between HFD and HFD+XN.csv", row.names = 1, stringsAsFactors = FALSE)
head(shared)
```

```{r}
library(DESeq2)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
```

```{r}
heatmap = pheatmap(shared, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlBu")))(30), fontsize_number = 1.5, cluster_rows = T)
```

```{r}
shared_2 = shared[order(shared$log2FC.HFD),]
```

```{r}
shared_2 = shared[rev(heatmap$tree_row$order),]
shared_2 = shared[c(rev(heatmap$tree_row$order[1:90]), rev(heatmap$tree_row$order[91:243])),]
shared_2 = shared_2[rev(row.names(shared_2)),]
```

```{r}
heatmap$tree_row$order
```

```{r}
row.names(metabolic_df_2) = metabolic_df_2$Symbol
```

```{r}
setwd("~/Desktop/FXR analysis/Fxr/Data")
jpeg("heat map of shared genes.jpeg", width = 1000, height = 3000)
pheatmap(shared_2, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlBu")))(30), fontsize_number = 4, cluster_rows = F)
dev.off()
```
